# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  view:
    view_response_listener: true
  format_listener:
    rules:
      - { path: '^/api/', priorities: ['json'], fallback_format: 'json' }
      - { path: '^/', priorities: ['html'], fallback_format: 'html' }
  exception:
    enabled: true
    messages:
      'Symfony\Component\HttpKernel\Exception\HttpException': true
      'Symfony\Component\Security\Core\Exception\BadCredentialsException': true # pour conserver le message d'erreur et ne pas le remplacer par "Internal Server Error"
    codes:
      'Symfony\Component\Security\Core\Exception\BadCredentialsException': 401 # attribue le code d'erreur 401 au lieu de 500
    exception_controller: 'fos_rest.exception.controller:showAction'

    #body_listener:
    #enabled: true
  param_fetcher_listener:
    enabled: true

  serializer:
    serialize_null:  true